
version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'O80kXYIAQrUdhmrr5VjjnSbz1xWtlyxhdqAUbihKTKg='
      AIRFLOW__WEBSERVER__SECRET_KEY: "mO80kXYIAQrUdhmrr5VjjnSbz1xWtlyxhdqAUbihKTKg="
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__TASK_RUNNER: StandardTaskRunner
    volumes:
      - ./dags:/opt/airflow/dags
      - ./Data:/Data
      - C:/Users/husse/.aws:/home/airflow/.aws:ro
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'O80kXYIAQrUdhmrr5VjjnSbz1xWtlyxhdqAUbihKTKg='
      AIRFLOW__WEBSERVER__SECRET_KEY: "mO80kXYIAQrUdhmrr5VjjnSbz1xWtlyxhdqAUbihKTKg="
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__TASK_RUNNER: StandardTaskRunner
    volumes:
      - ./dags:/opt/airflow/dags
      - ./Data:/Data
      - C:/Users/husse/.aws:/home/airflow/.aws:ro
    command: scheduler

volumes:
  postgres-db-volume:
